Add DAL for UserProfileService #3
vladzhorov/ServiceFinder pull request #14
Opened 2024-05-23 13:38 UTC by vladzhorov

2024-05-23 13:50 UTC, moltenessence requested changes

2024-05-23 13:50 UTC, moltenessence commented on ServiceFinder/ServiceFinder.DAL/DalServiceExtension.cs
> +                    serviceProvider.GetRequiredService<SoftDeleteInterceptor>());
Better to use optionsBuilder.AddInterceptors() to register interceptors. You can create objects via constructor

2024-05-23 13:50 UTC, moltenessence commented on ServiceFinder/ServiceFinder.DAL/Entites/ServiceEntity.cs
> +        public string Description { get; set; }
warnings not fixed for the file

2024-05-23 13:50 UTC, moltenessence commented on ServiceFinder/ServiceFinder.DAL/Entites/ServiceCategoryEntity.cs
> +        public bool IsDeleted { get; set; }
warnings

2024-05-23 13:50 UTC, moltenessence commented on ServiceFinder/ServiceFinder.DAL/Entites/ReviewEntity.cs
> +        public Guid ServiceId { get; set; }
warnings

2024-05-24 09:39 UTC, moltenessence approved these changes

2024-05-24 16:07 UTC, pavelGagarin0870 approved these changes

2024-05-24 21:22 UTC, merged