Add bll for UserProfileService #4
vladzhorov/ServiceFinder pull request #15
Opened 2024-05-27 23:04 UTC by vladzhorov

2024-05-28 07:38 UTC, moltenessence requested changes

2024-05-28 07:38 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Abstarctions/Services/IGenericService.cs
> +    public interface IGenericService<TEntity, TModel>
'TEntity' is not used in the interface.

2024-05-28 07:38 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Models/Review.cs
> +        public bool IsDeleted { get; set; }
Do you need this 'IsDeleted' flag here?

2024-05-28 07:38 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Models/ServiceCategory.cs
> +        public bool IsDeleted { get; set; }
same

2024-05-28 07:38 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Services/GenericService.cs
> +        {
formatting

2024-05-28 07:38 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Services/GenericService.cs
> +            var model = _mapper.Map<TModel>(entity);
what's the purpose of the cancellation token if you do not use it in repo, lol?

2024-05-28 07:38 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Services/GenericService.cs
> +            await _repository.DeleteAsync(entity, cancellationToken);
fix warnings

2024-05-28 07:38 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Models/UserProfile.cs
> +        public bool IsDeleted { get; set; }
same

2024-05-28 07:38 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Models/Service.cs
> +        public bool IsDeleted { get; set; }
same

2024-05-29 09:32 UTC, moltenessence approved these changes

2024-05-29 13:15 UTC, pavelGagarin0870 approved these changes

2024-05-29 14:08 UTC, merged