Add Presentation Layer for UserProfileService #5
vladzhorov/ServiceFinder pull request #16
Opened 2024-05-29 14:50 UTC by vladzhorov

2024-05-29 14:55 UTC, moltenessence requested changes

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/AssistanceCategoryController.cs
> +            modelToUpdate.Id = id;
is this Presentation layer responsibility?

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/AssistanceController.cs
> +        private readonly IAssistanceService _AssistanceService;
naming: _A

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/AssistanceController.cs
> +            modelToUpdate.Id = id;
same

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/ReviewController.cs
> +            var Review = await _ReviewService.GetByIdAsync(id, cancellationToken);
naming

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/ReviewController.cs
> +        private readonly IReviewService _ReviewService;
naming

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/UserProfileController.cs
> +    [Route("api/usersProfile")]
move all routes to constants

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Mapper/Mapping.cs
> +                .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => DateTime.UtcNow))
??????????????????

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Mapper/Mapping.cs
> +                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => DateTime.UtcNow));
??????????????????????

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Mapper/Mapping.cs
> +                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => DateTime.UtcNow));
???????????????????

2024-05-29 14:55 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Mapper/Mapping.cs
> +                .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => DateTime.UtcNow));
wtf

2024-05-30 09:57 UTC, moltenessence requested changes

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/AssistanceCategoryController.cs
> +        private readonly IAssistanceCategoryService _AssistanceCategoryService;
naming conventions are not followed

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/AssistanceCategoryController.cs
> +    [Route(ApiRoutes.assistancesCategory)]
naming conventions are not followed

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/AssistanceController.cs
> +    [Route(ApiRoutes.assistances)]
naming conventions are not followed

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/AssistanceController.cs
> +            var Assistance = await _assistanceService.GetByIdAsync(id, cancellationToken);
naming conventions are not followed

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/ReviewController.cs
> +            var Review = await _reviewService.GetByIdAsync(id, cancellationToken);
naming conventions are not followed

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/ReviewController.cs
> +    [Route(ApiRoutes.reviews)]
naming conventions are not followed

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Controller/UserProfileController.cs
> +    [Route(ApiRoutes.usersProfile)]
naming conventions are not followed

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/DI/ApiRoutes.cs
> +        public const string assistancesCategory = "api/assistancesCategory";
"api" can be moved to separate variable

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/DI/ApiRoutes.cs
> +        public const string usersProfile = "api/usersProfile";
naming conventions are not followed

2024-05-30 09:57 UTC, moltenessence commented on ServiceFinder/ServiceFinder.DAL/Entites/BaseEntity.cs
> +    public class BaseEntity : IBaseEntity
what's the reason to add both class and interface?

2024-05-30 11:12 UTC, moltenessence approved these changes

2024-05-30 14:23 UTC, VadimZharikov approved these changes

2024-05-30 14:33 UTC, merged