Add pagiantion for /GET endpoints
vladzhorov/ServiceFinder pull request #35
Opened 2024-06-13 16:45 UTC by vladzhorov

2024-06-19 15:13 UTC, moltenessence requested changes

2024-06-19 15:13 UTC, moltenessence commented on ServiceFinder/ServiceFinder.API/Mapper/Mapping.cs
> +            CreateMap(typeof(PagedResult<>), typeof(PagedResult<>));
???

2024-06-19 15:13 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Mapper/Mapping.cs
> +            CreateMap(typeof(PagedResult<>), typeof(PagedResult<>));
???

2024-06-19 15:13 UTC, moltenessence commented on ServiceFinder/ServiceFinder.BLL/Services/GenericService.cs
> +                Data = models
Setup automapper for these fields

2024-06-19 16:55 UTC, moltenessence approved these changes

2024-06-21 08:41 UTC, pavelGagarin0870 approved these changes

2024-06-21 08:50 UTC, merged