Add average rating calculation
vladzhorov/ServiceFinder pull request #36
Opened 2024-06-21 14:00 UTC by vladzhorov

2024-06-24 10:21 UTC, daniilbluetape requested changes

2024-06-24 10:21 UTC, daniilbluetape commented on ServiceFinder/ServiceFinder.BLL/Services/AssistanceCategoryService.cs
> +        private readonly IAssistanceCategoryRepository _assistanceCategoryRepository;
Remove this unread private field '_assistanceCategoryRepository' or refactor the code to use its value. (https://rules.sonarsource.com/csharp/RSPEC-4487)

2024-06-24 10:21 UTC, daniilbluetape commented on ServiceFinder/ServiceFinder.BLL/Services/AssistanceCategoryService.cs
> +        private readonly IUserProfileRepository _userProfileRepository;
Remove this unread private field '_userProfileRepository' or refactor the code to use its value. (https://rules.sonarsource.com/csharp/RSPEC-4487)

2024-06-24 10:21 UTC, daniilbluetape commented on ServiceFinder/ServiceFinder.BLL/Services/RatingCalculatorService.cs
> +}
You don't need service to calculate average number in one specific model

2024-06-24 13:04 UTC, moltenessence approved these changes

2024-06-27 09:31 UTC, pavelGagarin0870 approved these changes

2024-06-27 09:34 UTC, merged