Add integration test
vladzhorov/ServiceFinder pull request #39
Opened 2024-06-27 10:04 UTC by vladzhorov

2024-06-27 12:24 UTC, moltenessence approved these changes

2024-06-27 12:44 UTC, Mmishaaa requested changes
and in other cases as well

2024-06-27 12:44 UTC, Mmishaaa commented on ServiceFinder/ServiceFinder.IntegrationTest/IntegrationTest/AssistanceControllerTest.cs
> +            response.EnsureSuccessStatusCode();
same

2024-06-27 12:44 UTC, Mmishaaa commented on ServiceFinder/ServiceFinder.IntegrationTest/IntegrationTest/AssistanceControllerTest.cs
> +            response.EnsureSuccessStatusCode();
same

2024-06-27 12:44 UTC, Mmishaaa commented on ServiceFinder/ServiceFinder.IntegrationTest/IntegrationTest/AssistanceControllerTest.cs
> +            response.EnsureSuccessStatusCode();
same

2024-06-27 12:44 UTC, Mmishaaa commented on ServiceFinder/ServiceFinder.IntegrationTest/IntegrationTest/AssistanceCategoryControllerTest.cs
> +            response.EnsureSuccessStatusCode();
same

2024-06-27 12:44 UTC, Mmishaaa commented on ServiceFinder/ServiceFinder.IntegrationTest/IntegrationTest/AssistanceCategoryControllerTest.cs
> +            response.EnsureSuccessStatusCode();
same

2024-06-30 13:07 UTC, Mmishaaa approved these changes

2024-06-30 15:43 UTC, merged