Setup notifications service
vladzhorov/ServiceFinder pull request #55
Opened 2024-07-01 11:03 UTC by vladzhorov

2024-07-01 11:26 UTC, moltenessence approved these changes

2024-07-01 11:29 UTC, moltenessence requested changes
The layers you chose not applicable to this service

2024-07-17 10:19 UTC, moltenessence approved these changes

2024-07-17 10:47 UTC, Mmishaaa approved these changes

2024-07-17 10:50 UTC, merged