Implement infrastructure layer
vladzhorov/ServiceFinder pull request #58
Opened 2024-07-04 14:06 UTC by vladzhorov

2024-07-06 10:18 UTC, moltenessence approved these changes

2024-07-09 10:26 UTC, 5Ka-me approved these changes

2024-07-09 14:41 UTC, Mmishaaa requested changes

2024-07-09 14:41 UTC, Mmishaaa commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Infrastructure/Repositories/Repository.cs
> +        public async virtual Task<PagedResult<T>> GetAllAsync(int pageNumber, int pageSize, CancellationToken cancellationToken)
async/await could be removed

2024-07-09 14:41 UTC, Mmishaaa commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Infrastructure/Repositories/Repository.cs
> +        public async virtual Task<IEnumerable<T>> GetByPredicateAsync(Expression<Func<T, bool>> predicate, CancellationToken cancellationToken)
async/await could be removed

2024-07-10 09:27 UTC, Mmishaaa approved these changes

2024-07-10 10:05 UTC, merged