Implement application
vladzhorov/ServiceFinder pull request #60
Opened 2024-07-10 10:50 UTC by vladzhorov

2024-07-10 16:02 UTC, pavelGagarin0870 approved these changes

2024-07-10 19:18 UTC, moltenessence requested changes

2024-07-10 19:18 UTC, moltenessence commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/ApplicationExtension.cs
> +            services.Configure<RabbitMQConfiguration>(options => configuration.GetSection("RabbitMQ").Bind(options));
move section name to constants

2024-07-10 19:18 UTC, moltenessence commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/ApplicationExtension.cs
> +                                  routingKey: options.Queue.RoutingKey);
I don't understand what's the queue is from its naming

2024-07-10 19:18 UTC, moltenessence commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/EventHandlers/OrderRequestStatusChangedEventHandler.cs
> +    public class OrderRequestStatusChangedEventHandler
Why don't you use interface?

2024-07-10 19:18 UTC, moltenessence commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/Mapper/OrderMappingProfile.cs
> +            CreateMap<OrderDto, Order>();
.ReverseMap()

2024-07-10 19:18 UTC, moltenessence commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/Mapper/OrderMappingProfile.cs
> +            CreateMap<OrderRequestDto, OrderRequest>();
same

2024-07-10 19:18 UTC, moltenessence commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/Services/OrderRequestAppService.cs
> +        }
Avoid state machine generation under the hood

2024-07-11 09:57 UTC, moltenessence approved these changes

2024-07-11 10:18 UTC, Mmishaaa requested changes

2024-07-11 10:18 UTC, Mmishaaa commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/ApplicationExtension.cs
> +            services.AddScoped<OrderStatusChangedEventHandler>();
no interfaces decalred

2024-07-11 10:18 UTC, Mmishaaa commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/EventHandlers/OrderRequestStatusChangedEventHandler.cs
> +    public class OrderRequestStatusChangedEventHandler
same

2024-07-11 10:18 UTC, Mmishaaa commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Application/EventHandlers/OrderStatusChangedEventHandler .cs
> +    public class OrderStatusChangedEventHandler
interface missed

2024-07-11 10:55 UTC, Mmishaaa approved these changes

2024-07-11 10:55 UTC, Mmishaaa commented on ServiceFinder.OrderService/ServiceFinder.OrderService.Domain/Interfaces/IRepository.cs
> +        PagedResult<T> GetAll(int pageNumber, int pageSize);
why not async

2024-07-11 11:05 UTC, merged